Args: --data_dir=/workspace/data --log_dir=$RUNDIR
Cmd: hello.py
EnvVars: []
ExecutionDir: /src/tensorflow-py2
Images:
  BaseImage: tensorflow/tensorflow
  GpuImage: tensorflow/tensorflow:latest-gpu
  PSImage: tensorflow/tensorflow
Jupyter:
  UseGPU: false
  Image: kuberlab/mlboard-jupyter-gpu:latest
  CPU: 100m
  CPULimit: 8000m
  Memory: 128Mi
  MemoryLimit: 4Gi
MonitoringNamespace: kuberlab
Requests:
  CPU: 100m
  CPULimit: 8000m
  GPU: 0
  Memory: 128Mi
  MemoryLimit: 8Gi
  PsPods: 0
  WorkerPods: 0
Volumes:
- isLibDir: false
  isTrainLogDir: true
  mountPath: /training
  name: training
  clusterStorage: {{ .storage }}
  subPath: training
- gitRepo:
    repository: https://github.com/kuberlab-catalog/tensorflow-py2
  isLibDir: false
  isTrainLogDir: false
  mountPath: /src
  name: src
  subPath: ""
- isLibDir: true
  isTrainLogDir: false
  mountPath: /workspace/lib
  name: lib
  clusterStorage: {{ .storage }}
  subPath: lib
- isLibDir: false
  isTrainLogDir: false
  mountPath: /workspace/data
  name: data
  clusterStorage: {{ .storage }}
  subPath: data
